# Generated by Django 5.1.5 on 2025-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_history', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchponghistory',
            name='score',
            field=models.CharField(default='0 - 0', max_length=10),
        ),
    ]
