# Generated by Django 5.1.4 on 2025-01-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0002_alter_matchhistory_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='opponent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
