# Generated by Django 5.1.2 on 2024-11-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friendship_accepted_alter_friendship_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
    ]
