# Generated by Django 5.1.2 on 2024-11-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_friendship_accepted_at_friendship_accepted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
    ]
