# Generated by Django 5.1.6 on 2025-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gameinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvite',
            name='init_oponente',
            field=models.IntegerField(default=0),
        ),
    ]
